/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWorldRouteImport } from './routes/_authenticated/world'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPulseRouteImport } from './routes/_authenticated/pulse'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedLuaVaultRouteImport } from './routes/_authenticated/lua-vault'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedBackendRouteImport } from './routes/_authenticated/backend'
import { Route as AuthenticatedAnalyzerRouteImport } from './routes/_authenticated/analyzer'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedTabsSlugRouteImport } from './routes/_authenticated/tabs.$slug'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksWatcherTickRouteImport } from './routes/api/public/hooks/watcher-tick'
import { Route as ApiPublicHooksIngestCashappRouteImport } from './routes/api/public/hooks/ingest-cashapp'
import { Route as ApiPublicHooksDailyDiscordRouteImport } from './routes/api/public/hooks/daily-discord'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorldRoute = AuthenticatedWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPulseRoute = AuthenticatedPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLuaVaultRoute = AuthenticatedLuaVaultRouteImport.update({
  id: '/lua-vault',
  path: '/lua-vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackendRoute = AuthenticatedBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyzerRoute = AuthenticatedAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTabsSlugRoute = AuthenticatedTabsSlugRouteImport.update({
  id: '/tabs/$slug',
  path: '/tabs/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWatcherTickRoute =
  ApiPublicHooksWatcherTickRouteImport.update({
    id: '/api/public/hooks/watcher-tick',
    path: '/api/public/hooks/watcher-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestCashappRoute =
  ApiPublicHooksIngestCashappRouteImport.update({
    id: '/api/public/hooks/ingest-cashapp',
    path: '/api/public/hooks/ingest-cashapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDiscordRoute =
  ApiPublicHooksDailyDiscordRouteImport.update({
    id: '/api/public/hooks/daily-discord',
    path: '/api/public/hooks/daily-discord',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lab': typeof AuthenticatedLabRoute
  '/lua-vault': typeof AuthenticatedLuaVaultRoute
  '/map': typeof AuthenticatedMapRoute
  '/pulse': typeof AuthenticatedPulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/time': typeof AuthenticatedTimeRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/world': typeof AuthenticatedWorldRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/tabs/$slug': typeof AuthenticatedTabsSlugRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/hooks/daily-discord': typeof ApiPublicHooksDailyDiscordRoute
  '/api/public/hooks/ingest-cashapp': typeof ApiPublicHooksIngestCashappRoute
  '/api/public/hooks/watcher-tick': typeof ApiPublicHooksWatcherTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analyzer': typeof AuthenticatedAnalyzerRoute
  '/backend': typeof AuthenticatedBackendRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lab': typeof AuthenticatedLabRoute
  '/lua-vault': typeof AuthenticatedLuaVaultRoute
  '/map': typeof AuthenticatedMapRoute
  '/pulse': typeof AuthenticatedPulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/time': typeof AuthenticatedTimeRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/world': typeof AuthenticatedWorldRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/tabs/$slug': typeof AuthenticatedTabsSlugRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/hooks/daily-discord': typeof ApiPublicHooksDailyDiscordRoute
  '/api/public/hooks/ingest-cashapp': typeof ApiPublicHooksIngestCashappRoute
  '/api/public/hooks/watcher-tick': typeof ApiPublicHooksWatcherTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analyzer': typeof AuthenticatedAnalyzerRoute
  '/_authenticated/backend': typeof AuthenticatedBackendRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/lua-vault': typeof AuthenticatedLuaVaultRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/pulse': typeof AuthenticatedPulseRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/world': typeof AuthenticatedWorldRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/tabs/$slug': typeof AuthenticatedTabsSlugRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/hooks/daily-discord': typeof ApiPublicHooksDailyDiscordRoute
  '/api/public/hooks/ingest-cashapp': typeof ApiPublicHooksIngestCashappRoute
  '/api/public/hooks/watcher-tick': typeof ApiPublicHooksWatcherTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analyzer'
    | '/backend'
    | '/briefing'
    | '/dashboard'
    | '/lab'
    | '/lua-vault'
    | '/map'
    | '/pulse'
    | '/settings'
    | '/time'
    | '/vault'
    | '/world'
    | '/api/chat'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/tabs/$slug'
    | '/chat/'
    | '/api/public/hooks/daily-discord'
    | '/api/public/hooks/ingest-cashapp'
    | '/api/public/hooks/watcher-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analyzer'
    | '/backend'
    | '/briefing'
    | '/dashboard'
    | '/lab'
    | '/lua-vault'
    | '/map'
    | '/pulse'
    | '/settings'
    | '/time'
    | '/vault'
    | '/world'
    | '/api/chat'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/tabs/$slug'
    | '/chat'
    | '/api/public/hooks/daily-discord'
    | '/api/public/hooks/ingest-cashapp'
    | '/api/public/hooks/watcher-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analyzer'
    | '/_authenticated/backend'
    | '/_authenticated/briefing'
    | '/_authenticated/dashboard'
    | '/_authenticated/lab'
    | '/_authenticated/lua-vault'
    | '/_authenticated/map'
    | '/_authenticated/pulse'
    | '/_authenticated/settings'
    | '/_authenticated/time'
    | '/_authenticated/vault'
    | '/_authenticated/world'
    | '/api/chat'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/tabs/$slug'
    | '/_authenticated/chat/'
    | '/api/public/hooks/daily-discord'
    | '/api/public/hooks/ingest-cashapp'
    | '/api/public/hooks/watcher-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksDailyDiscordRoute: typeof ApiPublicHooksDailyDiscordRoute
  ApiPublicHooksIngestCashappRoute: typeof ApiPublicHooksIngestCashappRoute
  ApiPublicHooksWatcherTickRoute: typeof ApiPublicHooksWatcherTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/world': {
      id: '/_authenticated/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof AuthenticatedWorldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pulse': {
      id: '/_authenticated/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AuthenticatedPulseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lua-vault': {
      id: '/_authenticated/lua-vault'
      path: '/lua-vault'
      fullPath: '/lua-vault'
      preLoaderRoute: typeof AuthenticatedLuaVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backend': {
      id: '/_authenticated/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof AuthenticatedBackendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyzer': {
      id: '/_authenticated/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AuthenticatedAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabs/$slug': {
      id: '/_authenticated/tabs/$slug'
      path: '/tabs/$slug'
      fullPath: '/tabs/$slug'
      preLoaderRoute: typeof AuthenticatedTabsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watcher-tick': {
      id: '/api/public/hooks/watcher-tick'
      path: '/api/public/hooks/watcher-tick'
      fullPath: '/api/public/hooks/watcher-tick'
      preLoaderRoute: typeof ApiPublicHooksWatcherTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-cashapp': {
      id: '/api/public/hooks/ingest-cashapp'
      path: '/api/public/hooks/ingest-cashapp'
      fullPath: '/api/public/hooks/ingest-cashapp'
      preLoaderRoute: typeof ApiPublicHooksIngestCashappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-discord': {
      id: '/api/public/hooks/daily-discord'
      path: '/api/public/hooks/daily-discord'
      fullPath: '/api/public/hooks/daily-discord'
      preLoaderRoute: typeof ApiPublicHooksDailyDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyzerRoute: typeof AuthenticatedAnalyzerRoute
  AuthenticatedBackendRoute: typeof AuthenticatedBackendRoute
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedLuaVaultRoute: typeof AuthenticatedLuaVaultRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedPulseRoute: typeof AuthenticatedPulseRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWorldRoute: typeof AuthenticatedWorldRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedTabsSlugRoute: typeof AuthenticatedTabsSlugRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyzerRoute: AuthenticatedAnalyzerRoute,
  AuthenticatedBackendRoute: AuthenticatedBackendRoute,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedLuaVaultRoute: AuthenticatedLuaVaultRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedPulseRoute: AuthenticatedPulseRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWorldRoute: AuthenticatedWorldRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedTabsSlugRoute: AuthenticatedTabsSlugRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksDailyDiscordRoute: ApiPublicHooksDailyDiscordRoute,
  ApiPublicHooksIngestCashappRoute: ApiPublicHooksIngestCashappRoute,
  ApiPublicHooksWatcherTickRoute: ApiPublicHooksWatcherTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
